@extends('layouts.app')

@php
    $content = [
        'shipping' => ['Shipping & Delivery', 'How we prepare and deliver your order.', [['Order confirmation', 'We begin preparing an order after it is confirmed. Product availability and delivery coverage are confirmed at checkout or through our support team.'], ['Delivery estimates', 'The current standard delivery estimate is shown during checkout. Estimates are guidance, not guaranteed delivery dates, because transit can be affected by location, weather, and carrier operations.'], ['Address accuracy', 'Please provide a complete delivery address, pincode, and reachable phone number. Contact us promptly if a correction is needed.'], ['Delivery support', 'If you need help with a delivery, contact Seed Planta with your order number and we will review the available options.']]],
        'returns' => ['Returns & Refunds', 'Our approach to order issues and support.', [['Seed products', 'Seeds and other agricultural goods can be sensitive to storage and handling. Eligibility for a return, replacement, or refund is assessed case by case after we review the order and issue reported.'], ['Report an issue', 'Please contact us as soon as possible with your order number, a clear description, and photos where relevant. Keep the original pack and order details available until we respond.'], ['Approved resolution', 'Where an issue is verified, the available resolution may be a replacement, store credit, or refund. The method and timing will be confirmed with you before it is processed.'], ['Cancellations', 'Orders may be cancelled only before they have moved to a non-cancellable fulfilment stage. You can request a cancellation from your order page or by contacting us.']]],
        'privacy' => ['Privacy Policy', 'How Seed Planta uses customer information.', [['Information we collect', 'We collect information you provide to create an account, place an order, contact support, or submit a review. This can include your name, contact details, delivery address, and order information.'], ['How we use it', 'We use this information to provide the store, process and support orders, respond to enquiries, prevent misuse, and improve our service.'], ['Sharing', 'We do not sell personal information. We may share only the information needed with service providers that help deliver an order, process a payment, or operate the store.'], ['Your choices', 'You may request access to or correction of your account information by contacting us. Some records may need to be retained where required for legitimate business or legal reasons.']]],
        'terms' => ['Terms & Conditions', 'The basic terms for using Seed Planta.', [['Store information', 'Product photos, descriptions, pricing, and availability are presented in good faith and may change as stock or supplier information changes.'], ['Orders', 'Submitting an order request does not guarantee acceptance. We may need to confirm availability, delivery coverage, or other details before fulfilment.'], ['Growing results', 'Germination and growing outcomes depend on variety, storage, season, soil, climate, and care. Follow appropriate local growing practices and product guidance.'], ['Acceptable use', 'Please use the site lawfully and do not attempt to interfere with the store, accounts, or checkout process.'], ['Policy updates', 'We may update these terms and policies as the business changes. The version available on the site applies to future use of the store.']]],
    ][$policy];
@endphp

@php($customContent = \App\Models\Setting::get('policy_'.$policy))

@section('title', $content[0].' — Seed Planta')

@section('content')
<main class="policy-page"><header><a href="{{ route('shop.index') }}" class="policy-page__brand"><x-site-logo class="logo__icon" /></a><a href="{{ route('shop.index') }}" class="text-link">← Back to shop</a></header><section class="policy-page__hero"><span class="section-eyebrow">Seed Planta policies</span><h1>{{ $content[0] }}</h1><p>{{ $content[1] }}</p></section><section class="policy-page__content">@if (filled($customContent))<article class="policy-page__custom-content">{!! nl2br(e($customContent)) !!}</article>@else @foreach ($content[2] as [$heading, $copy])<article><h2>{{ $heading }}</h2><p>{{ $copy }}</p></article>@endforeach @endif</section><footer>Last updated: {{ now()->format('F Y') }} · For policy questions, <a href="{{ route('contact.show') }}">contact Seed Planta</a>.</footer></main>
@endsection
