<?php

return [

    'whatsapp_number' => env('WHATSAPP_NUMBER', '919876543210'),

    'currency' => '₹',

    'tagline' => 'Quality seeds for your farm & garden',

    'categories' => [
        'vegetables' => 'Vegetables',
        'fruits' => 'Fruits',
        'flowers' => 'Flowers',
        'grains' => 'Grains',
    ],

    'products' => [
        [
            'id' => 1,
            'name' => 'Tomato Hybrid F1',
            'category' => 'vegetables',
            'price' => 120,
            'unit' => '50g pack',
            'description' => 'High-yield hybrid tomato seeds, disease resistant.',
            'emoji' => '🍅',
        ],
        [
            'id' => 2,
            'name' => 'Green Chilli',
            'category' => 'vegetables',
            'price' => 80,
            'unit' => '25g pack',
            'description' => 'Spicy green chilli variety, ideal for Indian climate.',
            'emoji' => '🌶️',
        ],
        [
            'id' => 3,
            'name' => 'Brinjal (Baingan)',
            'category' => 'vegetables',
            'price' => 95,
            'unit' => '50g pack',
            'description' => 'Purple long brinjal seeds with excellent germination.',
            'emoji' => '🍆',
        ],
        [
            'id' => 4,
            'name' => 'Okra (Bhindi)',
            'category' => 'vegetables',
            'price' => 75,
            'unit' => '100g pack',
            'description' => 'Tender okra variety, suitable for kharif season.',
            'emoji' => '🥒',
        ],
        [
            'id' => 5,
            'name' => 'Spinach (Palak)',
            'category' => 'vegetables',
            'price' => 60,
            'unit' => '100g pack',
            'description' => 'Nutritious leafy green, quick growing.',
            'emoji' => '🥬',
        ],
        [
            'id' => 6,
            'name' => 'Watermelon',
            'category' => 'fruits',
            'price' => 150,
            'unit' => '50g pack',
            'description' => 'Sweet red flesh watermelon, summer favourite.',
            'emoji' => '🍉',
        ],
        [
            'id' => 7,
            'name' => 'Muskmelon',
            'category' => 'fruits',
            'price' => 130,
            'unit' => '50g pack',
            'description' => 'Aromatic muskmelon with high sugar content.',
            'emoji' => '🍈',
        ],
        [
            'id' => 8,
            'name' => 'Papaya',
            'category' => 'fruits',
            'price' => 110,
            'unit' => '25 seeds',
            'description' => 'Dwarf papaya variety for home gardens.',
            'emoji' => '🥭',
        ],
        [
            'id' => 9,
            'name' => 'Marigold Orange',
            'category' => 'flowers',
            'price' => 55,
            'unit' => '10g pack',
            'description' => 'Bright orange marigold for borders & festivals.',
            'emoji' => '🌼',
        ],
        [
            'id' => 10,
            'name' => 'Sunflower Giant',
            'category' => 'flowers',
            'price' => 90,
            'unit' => '50g pack',
            'description' => 'Tall sunflower with large blooms.',
            'emoji' => '🌻',
        ],
        [
            'id' => 11,
            'name' => 'Rose Mixed',
            'category' => 'flowers',
            'price' => 140,
            'unit' => '20 seeds',
            'description' => 'Mixed colour rose seeds for pots & beds.',
            'emoji' => '🌹',
        ],
        [
            'id' => 12,
            'name' => 'Wheat HD-2967',
            'category' => 'grains',
            'price' => 200,
            'unit' => '1 kg pack',
            'description' => 'High-yield wheat variety for rabi season.',
            'emoji' => '🌾',
        ],
        [
            'id' => 13,
            'name' => 'Paddy Basmati',
            'category' => 'grains',
            'price' => 250,
            'unit' => '1 kg pack',
            'description' => 'Premium basmati paddy seeds.',
            'emoji' => '🍚',
        ],
        [
            'id' => 14,
            'name' => 'Mustard (Sarson)',
            'category' => 'grains',
            'price' => 85,
            'unit' => '500g pack',
            'description' => 'Oil-rich mustard seeds for winter crop.',
            'emoji' => '🌿',
        ],
    ],

];
